_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SSRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeadsSS"
    NUM_CLASSES: 12
  SS:
    FEAT_LEVEL: "res4"
    NAME: ["build_cycle_energy_direct_add_all_head"]
    LOSS_SCALE: 0.0
    RATIO: 2.0
    COEF: 1.0
    FILTERING1: 0.4
    FILTERING2: 0.6
    ENERGY_WEIGHT: 0.05
DATASETS:
  TRAIN: ("esmart_wip",)
SOLVER:
  IMS_PER_BATCH: 1
#   IMS_PER_BATCH: 16
  BASE_LR: 0.02
#  STEPS: (31200, 41600,)
#  MAX_ITER: 45500
  STEPS: (36000, 48000,)
  MAX_ITER: 52500
  WARMUP_ITERS: 2500
  CHECKPOINT_PERIOD: 1000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  RANDOM_FLIP: "none"
  CROP:
    ENABLED: True
SEED: 34112225
DATALOADER:
  SAMPLER_TRAIN: "PairTrainingMultiRandomSampler"
  PAIR_OFFSET_RANGE: 200
  SELCTED_NUMBER: 3
OUTPUT_DIR: "checkpoints/esmart/trial_9_window"